name: E2E Test

on:
  pull_request:
    branches:
      - main
      - dev
  push:
    branches:
      - main

jobs:
  pylint:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: ["3.10", "3.11"]
        os: [ubuntu-latest]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          poetry install

      - name: Setting env vars
        run: |
          echo "GITHUB_PAT=${{ secrets.GH_PAT }}\n" >> .env
          echo "GITHUB_APP_ID=${{ secrets.GH_APP_ID }}\n" >> .env
          echo "GITHUB_APP_PEM=${{ secrets.GH_APP_PEM }}\n" >> .env

      - name: Run e2e test
        run: poetry run python tests/e2e/test_sweep_issue.py
